name: Node.js CI/CD

on:
  push:
    branches: [ main ]  # Trigger the workflow on push events to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup SSH key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
        echo "Private key fingerprint:"
        ssh-keygen -l -E md5 -f ~/.ssh/id_rsa

    - name: Debug SSH connection
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "Attempting to connect to $SERVER_USER@$SERVER_IP"
        ssh -v -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP exit

    - name: Deploy to local server
      env:
        SERVER_IP: ${{ secrets.SERVER_IP }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
        cd /home/ubuntu/Mindforge
        git pull origin main
        cd /home/ubuntu/Mindforge/website
        bun run build
        pm2 restart mindforge-web  # Or your preferred method to restart the Node.js app
        # Add any other necessary commands here
        # For example, you might want to call your custom API:
        # curl -X POST http://your-custom-api-endpoint/deploy